FROM python:3.6.6-slim-stretch

COPY requirements.txt .
RUN pip install --upgrade -r requirements.txt

COPY 020_api 020_api

ENTRYPOINT [ "python3.6", "/020_api/decision.py" ]

# sudo docker build --no-cache -t decision -f Dockerfile_decision .
# sudo docker run -p 5002:5002 decision