FROM python:3.6.6-slim-stretch

COPY requirements.txt .
RUN pip install --upgrade -r requirements.txt

COPY 020_api 020_api

ENTRYPOINT [ "python3.6", "/020_api/perception.py" ]

# sudo docker build --no-cache -t perception -f Dockerfile_perception .
# sudo docker run -p 5001:5001 perception